### ISSUE TITLE
Question: What is this repository?

### ISSUE THREAD

**Issue by neet** [aizwellenstan/refined-itsukara-ssr-2#1]
Hello @aizwellenstan, I'm the author of [neet/refined-itsukara-link](https://github.com/neet/refined-itsukara-link) (RIL, for short). When I was searching for my project on GitHub I realized that you cloned *RIL* multiple times. Which is a bit weird.
- https://github.com/search?q=itsukara

Could you tell me the purpose of the clones? *RIL* is distributed under the AGPL v3 license so your action is pretty legal but I'm still curious 😄 

If you had any trouble with deploying *RTL* just let me know on the issues of the original repository 👍

**Comment by aizwellenstan** [comment]
Just learning the tech from いちからの神 smile

**Comment by neet** [comment]
I’m glad to hear that! I hope my experiences help to you learn more about it 😘
